name: Pages Build

on:
  push:
    branches: [ main ]
    paths-ignore: [ 'docs/**' ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run website
      - run: |
          git config --global user.name 'ka9an'
          git config --global user.email 'ka66ann@gmail.com'
          git add -A
          git diff-index --quiet HEAD || git commit -m "chore: build pages" && git push
